{% set name = "sagemaker-chainer-container" %}
{% set version = "1.0.9.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 39a6b121bbca9f8e9ade4f4a9c92a16d3c6a193f1855c970be20cd653b4c5678

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - sagemaker_containers >=2.5
    - chainer >=5.0.0
    - retrying >=1.3.3
    - numpy >=1.15.2

test:
  imports:
    - sagemaker_chainer_container

about:
  home: https://github.com/aws/sagemaker-chainer-container
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Docker container for running Chainer scripts to train and host Chainer models on SageMaker.
  doc_url: https://github.com/aws/sagemaker-chainer-container
  dev_url: https://github.com/aws/sagemaker-chainer-container

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - benhuff
